### ISSUE TITLE
Plans to have an asynchronous client?

### ISSUE THREAD

**Issue by vinayan3** [DataDog/dogstatsd-python#23]
I read through the code and concluded the code is synchronous and it's doubtful if it's thread safe.

Are you guys planning to implement an asynchronous version? As the docs note for a running production server with metric points in a few places it might start to become heavy. The solution proposed by the docs is to sample but for counts of requests sampling might not be accurate.

**Comment by yannmh** [comment]
Closing. Please head over to [datadogpy](https://github.com/DataDog/datadogpy) which is threadsafe.
