### ISSUE TITLE
0.5.4 contains backwards incompatibility, and likely performance degradation in high volume

### ISSUE THREAD

**Issue by Julian** [DataDog/dogstatsd-python#29]
#25 stopped instances of `Statsd` from opening sockets in `__init__`, which is great! But it didn't define `fdel`, so the attribute, which is now a property, isn't deletable, or, more importantly, things that monkeypatch it (tests) cannot anymore.

I also expect there to be non-zero performance degradation on CPython specifically given that now every time you need a socket, you have a property. I don't have an easy way of measuring this since we don't use CPython, but I suspect you'll find some if you measure it in high enough volume. Using https://pypi.python.org/pypi/cached-property should mitigate it.

I can send a PR for one or both if agreeable.

**Comment by yannmh** [comment]
Thanks a lot @Julian for your feedback !

I just made a new PR #30  to workaround these issues.

**Comment by elijahandrews** [comment]
Just a heads up: if `0.5.4` is incompatible with `0.5.3`, the next version should be `1.0.0` according to [Semantic Versioning](http://semver.org/).

**Comment by yannmh** [comment]
Should be fixed in 0.5.5

Thanks for your feedbacks !
