### ISSUE TITLE
Rename statsd to dogstatsd

### ISSUE THREAD

**Issue by dcramer** [DataDog/dogstatsd-python#34]
We unfortunately cannot rely on the dogstatsd-python module as it replaces the default statsd module (and we need to effectively support both at the same time).

I realize this is a backwards incompatible change, but IMO it's worth it.

**Comment by dcramer** [comment]
Related: https://github.com/getsentry/sentry/pull/1604

**Comment by miketheman** [comment]
Have you taken a look at the currently-supported library
https://github.com/DataDog/datadogpy ? Should address these concerns.

**Comment by dcramer** [comment]
@miketheman ah missed that, thanks!
