### ISSUE TITLE
Send Error is Logged on Every Exception

### ISSUE THREAD

**Issue by devdazed** [DataDog/dogstatsd-python#9]
Currently if the Agent is down, the UDP send will fail resulting in [logging of an exception](https://github.com/DataDog/dogstatsd-python/blob/master/statsd.py#L139-L142).  In high volume applications this can lead to logs growing extremely fast.  

Would it be possible to have a limit to how much it logs (maybe once per second) or something that is possibly configurable?

**Comment by yannmh** [comment]
Moved to [datadogpy](https://github.com/yannmh/datadogpy).
